
export const rawText4 = `
** Question 1** Which document provides high-level, mandatory directives set by senior management to dictate an organization's security posture? Options: A Standard B Guideline C Policy D Procedure Correct Option: C Policy Keywords for Exam: governance, policy, standard, guideline, procedure, senior management Detailed Explanation:
A policy is a formal statement of intent and direction as defined by senior management. It is mandatory and sets the foundation for all other security documentation. Standards define specific requirements for technologies, guidelines offer recommendations, and procedures provide step-by-step instructions.

** Question 2** An organization is setting up a new data center and wants to ensure high availability for its critical servers. They decide to implement a system with multiple power supplies, redundant network cards, and clustered servers. This is an example of which security concept? Options: A Defense in depth B Least privilege C Redundancy D Separation of duties Correct Option: C Redundancy Keywords for Exam: high availability, availability, redundancy, fault tolerance, single point of failure Detailed Explanation:
Redundancy is the practice of duplicating critical components or functions of a system with the intention of increasing reliability and availability. This eliminates single points of failure. Defense in depth is a layered security approach, while least privilege and separation of duties are access control principles.

** Question 3** What is the primary purpose of a Business Impact Analysis (BIA)? Options: A To calculate the exact financial loss of a disaster B To identify and prioritize critical business functions and resources C To test the disaster recovery plan D To select a vendor for a hot site Correct Option: B To identify and prioritize critical business functions and resources Keywords for Exam: BIA, business impact analysis, business continuity, critical functions, RTO, RPO Detailed Explanation:
The primary goal of a Business Impact Analysis (BIA) is to identify the organization's critical business functions and determine the impact a disruption would have on them. This analysis is crucial for establishing Recovery Time Objectives (RTO) and Recovery Point Objectives (RPO) and forms the foundation of the Business Continuity Plan (BCP).

** Question 4** A user receives an email that appears to be from their bank, asking them to click a link and verify their account details. This is a classic example of what type of attack? Options: A Whaling B Vishing C Smishing D Phishing Correct Option: D Phishing Keywords for Exam: phishing, social engineering, email, fraudulent message, credential harvesting Detailed Explanation:
Phishing is a type of social engineering attack where an attacker sends fraudulent emails purporting to be from a reputable source to trick individuals into revealing sensitive information like passwords and credit card numbers. Whaling is phishing targeted at executives, vishing is voice phishing, and smishing is SMS phishing.

** Question 5** In the CIA triad, which principle ensures that data is not altered or destroyed in an unauthorized manner? Options: A Confidentiality B Integrity C Availability D Non-repudiation Correct Option: B Integrity Keywords for Exam: CIA triad, integrity, data alteration, accuracy, consistency, hashing Detailed Explanation:
Integrity is the 'I' in the CIA triad and refers to maintaining the consistency, accuracy, and trustworthiness of data over its entire lifecycle. It ensures that data has not been subject to unauthorized modification. Hashing is a common mechanism used to verify data integrity.

** Question 6** An organization wants to implement an access control model where permissions are assigned based on a user's job title, such as "Accountant" or "HR Manager". Which model would be most appropriate? Options: A Discretionary Access Control (DAC) B Mandatory Access Control (MAC) C Attribute-Based Access Control (ABAC) D Role-Based Access Control (RBAC) Correct Option: D Role-Based Access Control (RBAC) Keywords for Exam: access control, RBAC, role-based, job title, permissions, MAC, DAC, ABAC Detailed Explanation:
Role-Based Access Control (RBAC) is an access control model where permissions are assigned to roles, and users are then assigned to those roles. This simplifies administration, as permissions can be managed for a role rather than for each individual user. It's ideal for organizations where user functions are well-defined by job titles.

** Question 7** Which of the following is considered a 'preventive' security control? Options: A CCTV Camera B Firewall C Audit Log D Intrusion Detection System (IDS) Correct Option: B Firewall Keywords for Exam: security control, preventive, detective, corrective, firewall, IDS Detailed Explanation:
A preventive control is designed to stop a security incident from happening. A firewall is a classic example, as it actively blocks unauthorized network traffic based on a set of rules. CCTV cameras and IDS are detective controls (they detect an incident), and audit logs are used for detection and investigation.

** Question 8** After a security incident, a forensic investigator is analyzing data that was left on a hard drive even after the files were deleted. What is this type of data called? Options: A Data in transit B Data remnants C Data in use D Temporary data Correct Option: B Data remnants Keywords for Exam: data remnants, data destruction, sanitization, residual data, forensics Detailed Explanation:
Data remnants, also known as residual data, refer to the data that remains on storage media after common data removal procedures. Proper data destruction or sanitization techniques like degaussing or cryptographic erasure are required to eliminate data remnants and prevent their recovery.

** Question 9** An organization is choosing a disaster recovery site. They need a location that is fully equipped with hardware, software, and real-time data replication, allowing for an almost immediate switchover. What type of site is this? Options: A Hot site B Warm site C Cold site D Mobile site Correct Option: A Hot site Keywords for Exam: disaster recovery, recovery site, hot site, warm site, cold site, RTO Detailed Explanation:
A hot site is a fully functional disaster recovery facility with all the necessary hardware, software, and real-time data synchronization. It allows for the fastest recovery time (lowest RTO) but is also the most expensive option. A warm site has hardware but requires data to be restored, and a cold site is just a space with power and connectivity.

** Question 10** Which protocol is used to securely browse websites and encrypts the traffic between the browser and the web server? Options: A FTP B HTTP C SMTP D HTTPS Correct Option: D HTTPS Keywords for Exam: HTTPS, HTTP, TLS, SSL, encryption, port 443, network security Detailed Explanation:
HTTPS (Hypertext Transfer Protocol Secure) is the secure version of HTTP. It uses encryption protocols like TLS (Transport Layer Security) or its predecessor SSL to encrypt the communication channel, protecting the confidentiality and integrity of data exchanged between a user's browser and a website. It operates on port 443.

** Question 11** What is the main difference between symmetric and asymmetric encryption? Options: A Symmetric is faster than asymmetric B Symmetric uses two keys, while asymmetric uses one C Symmetric is only for data at rest, while asymmetric is for data in transit D Symmetric uses the same key for encryption and decryption, while asymmetric uses different keys Correct Option: D Symmetric uses the same key for encryption and decryption, while asymmetric uses different keys Keywords for Exam: encryption, symmetric, asymmetric, public key, private key, cryptography Detailed Explanation:
The fundamental difference lies in the keys used. Symmetric encryption uses a single, shared key for both encrypting and decrypting data. Asymmetric (or public-key) encryption uses a pair of keys: a public key to encrypt data and a private key to decrypt it.

** Question 12** According to the ISC2 Code of Ethics, acting honorably, honestly, justly, responsibly, and legally is part of which canon? Options: A Protect society, the common good B Act honorably, honestly, justly, responsibly, and legally C Provide diligent and competent service to principals D Advance and protect the profession Correct Option: B Act honorably, honestly, justly, responsibly, and legally Keywords for Exam: ISC2, ethics, canons, act honorably, due care Detailed Explanation:
This is the second canon of the ISC2 Code of Ethics. It requires members to maintain a high standard of professional conduct and to obey all laws and regulations.

** Question 13** A security administrator is configuring a system to require a password and a fingerprint scan for access. This is an implementation of what? Options: A Single-factor authentication B Two-person control C Multi-factor authentication D Defense in depth Correct Option: C Multi-factor authentication Keywords for Exam: authentication, MFA, multi-factor, something you know, something you are, something you have Detailed Explanation:
Multi-factor authentication (MFA) requires a user to provide two or more different types of authentication factors. In this case, a password is 'something you know' and a fingerprint is 'something you are'. Using factors from two different categories constitutes MFA.

** Question 14** What is the primary purpose of system hardening? Options: A To make the system run faster B To reduce the system's attack surface C To monitor system logs D To back up system data Correct Option: B To reduce the system's attack surface Keywords for Exam: hardening, configuration management, attack surface, security baseline Detailed Explanation:
System hardening is the process of securing a system by reducing its vulnerabilities. This is primarily achieved by minimizing its attack surface, which involves removing unnecessary software, disabling unused services, closing unused ports, and applying security patches.

** Question 15** A company has a policy that one person can approve invoices, but a different person must be the one to issue payments. This is an example of what security principle? Options: A Least privilege B Separation of duties C Two-person control D Job rotation Correct Option: B Separation of duties Keywords for Exam: separation of duties, access control, fraud detection, security principle Detailed Explanation:
Separation of duties is a security principle that prevents a single individual from having control over all aspects of a critical task. By splitting the responsibilities (approving vs. paying), the company reduces the risk of fraud and error.

** Question 16** An attacker floods a web server with so many requests that it becomes overwhelmed and cannot respond to legitimate users. What type of attack is this? Options: A Man-in-the-middle (MitM) B Denial of Service (DoS) C SQL Injection D Cross-Site Scripting (XSS) Correct Option: B Denial of Service (DoS) Keywords for Exam: DoS, DDoS, availability, network attack, flooding Detailed Explanation:
A Denial of Service (DoS) attack aims to make a machine or network resource unavailable to its intended users by disrupting services. This is typically accomplished by overwhelming the target with a flood of traffic or malicious requests, thus compromising its availability.

** Question 17** Which document is a non-binding agreement between two or more parties that outlines the terms and details of an understanding, including each party's requirements and responsibilities? Options: A Service Level Agreement (SLA) B Memorandum of Understanding (MOU) C Business Partnership Agreement (BPA) D Interconnection Security Agreement (ISA) Correct Option: B Memorandum of Understanding (MOU) Keywords for Exam: agreement, MOU, SLA, non-binding, informal agreement Detailed Explanation:
A Memorandum of Understanding (MOU) is a document that describes a bilateral or multilateral agreement between parties. It expresses a convergence of will between the parties, indicating an intended common line of action. It is often used in cases where parties do not imply a legal commitment or in situations where the parties cannot create a legally enforceable agreement. It is less formal than an SLA.

** Question 18** Which type of malware is specifically designed to replicate itself and spread to other computers, typically over a network, without human intervention? Options: A Virus B Trojan C Rootkit D Worm Correct Option: D Worm Keywords for Exam: malware, worm, virus, self-replicating, network propagation Detailed Explanation:
A worm is a standalone malware computer program that replicates itself in order to spread to other computers. It often uses a computer network to spread itself, relying on security failures on the target computer to access it. Unlike a virus, it does not need to attach itself to an existing program and does not require human action to spread.

** Question 19** What does a hash function provide? Options: A Confidentiality B Availability C Integrity D Authorization Correct Option: C Integrity Keywords for Exam: hashing, integrity, message digest, digital fingerprint, one-way function Detailed Explanation:
A hash function takes an input (or 'message') and returns a fixed-size string of bytes. The output, the 'hash' or 'message digest', is a unique digital fingerprint of the data. If the input data changes even slightly, the hash value will change completely. This property allows hashing to be used to verify data integrity.

** Question 20** An organization's acceptable use policy (AUP) is what type of security control? Options: A Physical B Technical C Administrative D Corrective Correct Option: C Administrative Keywords for Exam: security control, administrative, policy, AUP, preventive control Detailed Explanation:
Administrative (or managerial) controls are the policies, procedures, standards, and guidelines that direct how security is managed within an organization. An Acceptable Use Policy (AUP) is a document that defines the rules users must agree to in order to use a network or service, making it a classic example of an administrative control.

** Question 21** In the context of risk management, if an organization decides to purchase cybersecurity insurance, which risk treatment strategy are they employing? Options: A Risk Acceptance B Risk Mitigation C Risk Avoidance D Risk Transference Correct Option: D Risk Transference Keywords for Exam: risk management, risk transference, risk mitigation, insurance Detailed Explanation:
Risk transference, or risk sharing, is the strategy of moving the financial impact of a risk to a third party. Purchasing an insurance policy is the most common example of this, where the financial liability for a security breach is transferred to the insurance company.

** Question 22** Which layer of the OSI model is responsible for routing and forwarding IP packets? Options: A Layer 2 (Data Link) B Layer 3 (Network) C Layer 4 (Transport) D Layer 7 (Application) Correct Option: B Layer 3 (Network) Keywords for Exam: OSI model, network layer, layer 3, routing, IP address, router Detailed Explanation:
The Network Layer (Layer 3) is responsible for logical addressing (IP addresses) and determining the best path for data to travel from source to destination across multiple networks. Routers operate at this layer to make these forwarding decisions.

** Question 23** The final step in most incident response frameworks, such as the one from NIST, involves reviewing the incident and the team's performance to improve for the future. What is this phase called? Options: A Containment B Eradication C Recovery D Post-Incident Activity (or Lessons Learned) Correct Option: D Post-Incident Activity (or Lessons Learned) Keywords for Exam: incident response, NIST, lessons learned, post-incident, preparation Detailed Explanation:
The Post-Incident Activity phase is the final stage in the NIST incident response lifecycle (SP 800-61). It involves analyzing the incident and the response to it to identify lessons learned. This feedback loop is critical for improving security controls and the incident response process itself to better handle future incidents.

** Question 24** A firewall that inspects not only the packet header but also the data content of the packets to look for malicious activity is what kind of firewall? Options: A Packet-filtering firewall B Stateful inspection firewall C Next-generation firewall (NGFW) D Proxy firewall Correct Option: C Next-generation firewall (NGFW) Keywords for Exam: firewall, NGFW, deep packet inspection, application awareness Detailed Explanation:
A Next-Generation Firewall (NGFW) goes beyond traditional port/protocol inspection. It includes features like deep packet inspection (DPI), application awareness, and intrusion prevention capabilities, allowing it to make more intelligent decisions about traffic based on its content, not just its header information.

** Question 25** What security concept is violated when an administrator uses a shared account with a single password for all network devices? Options: A Confidentiality B Defense in Depth C Accountability D Availability Correct Option: C Accountability Keywords for Exam: accountability, non-repudiation, shared account, logging, auditing Detailed Explanation:
Accountability ensures that the actions of a person or system can be traced uniquely to that entity. When a shared account is used, it's impossible to know which specific individual performed an action, thereby destroying accountability and its related concept, non-repudiation.

** Question 26** Which of the following is an example of 'something you are' in authentication? Options: A A hardware token B A PIN code C A fingerprint D A smart card Correct Option: C A fingerprint Keywords for Exam: authentication factors, something you are, biometrics, MFA Detailed Explanation:
'Something you are' refers to biometric factors of authentication. These are unique physical characteristics of a person, such as a fingerprint, iris pattern, or facial geometry. Passwords and PINs are 'something you know', while tokens and smart cards are 'something you have'.

** Question 27** What does the principle of "least privilege" dictate? Options: A Users should have the maximum privileges needed to do their job and a little extra. B Users should have privileges assigned based on their role in the company. C Users should only be granted the minimum permissions necessary to perform their job functions. D Users should have their privileges reviewed at least once per year. Correct Option: C Users should only be granted the minimum permissions necessary to perform their job functions. Keywords for Exam: least privilege, access control, permissions, need-to-know Detailed Explanation:
The principle of least privilege is a cornerstone of access control. It states that a user, program, or process should have only the bare minimum privileges necessary to perform its specific, authorized tasks. This limits the potential damage from an accident, error, or malicious use of credentials.

** Question 28** An organization has determined that its critical sales system can be down for a maximum of 4 hours before causing significant business harm. What does this 4-hour window represent? Options: A Recovery Point Objective (RPO) B Mean Time To Repair (MTTR) C Recovery Time Objective (RTO) D Mean Time Between Failures (MTBF) Correct Option: C Recovery Time Objective (RTO) Keywords for Exam: RTO, RPO, BIA, disaster recovery, business continuity Detailed Explanation:
The Recovery Time Objective (RTO) is the target duration of time within which a business process must be restored after a disaster or disruption to avoid unacceptable consequences associated with a break in business continuity. In this case, the RTO is 4 hours.

** Question 29** What is the process of securely and permanently removing data from a storage medium called? Options: A Data Archiving B Data Encryption C Data Masking D Data Sanitization Correct Option: D Data Sanitization Keywords for Exam: data sanitization, data destruction, degaussing, cryptographic erase, data remnants Detailed Explanation:
Data sanitization is the process of deliberately, permanently, and irreversibly removing or destroying the data stored on a memory device. The purpose is to make the data unrecoverable. Methods include overwriting, degaussing, and physical destruction.

** Question 30** Which cloud computing service model provides the customer with a complete application that is managed by the provider? Options: A Infrastructure as a Service (IaaS) B Platform as a Service (PaaS) C Software as a Service (SaaS) D Anything as a Service (XaaS) Correct Option: C Software as a Service (SaaS) Keywords for Exam: cloud service models, SaaS, PaaS, IaaS, shared responsibility Detailed Explanation:
In the Software as a Service (SaaS) model, the cloud provider delivers and manages a complete application over the internet. The customer simply uses the software without worrying about the underlying infrastructure, platform, or application maintenance. Examples include web-based email and CRM software.

** Question 31** Which security goal is most compromised by a ransomware attack? Options: A Confidentiality B Integrity C Availability D Non-repudiation Correct Option: C Availability Keywords for Exam: ransomware, availability, CIA triad, encryption, malware Detailed Explanation:
Ransomware works by encrypting a victim's files, making them inaccessible. Since the authorized user can no longer access their own data, this is a direct attack on the principle of Availability. While confidentiality and integrity could also be compromised, the primary and immediate impact is on availability.

** Question 32** Which document is a mandatory, organization-wide directive that dictates acceptable and unacceptable actions? Options: A Standard B Guideline C Policy D Procedure Correct Option: C Policy Keywords for Exam: governance, policy, standard, mandatory, high-level Detailed Explanation:
A policy is a high-level document that is mandatory and applies organization-wide. It is created by senior management and sets the strategic direction for security. Policies state *what* needs to be done, but not *how* to do it.

** Question 33** What is the term for an attack that tricks a user into clicking on a malicious link by hiding it under legitimate-looking text or images? Options: A Clickjacking B Phishing C Typosquatting D Spoofing Correct Option: A Clickjacking Keywords for Exam: clickjacking, UI redress attack, social engineering, web attack Detailed Explanation:
Clickjacking, also known as a UI redress attack, is a malicious technique of tricking a user into clicking on something different from what the user perceives, thus potentially revealing confidential information or taking control of their computer while clicking on seemingly innocuous web pages.

** Question 34** A security team is performing a Business Impact Analysis (BIA). They determine that in a disaster, the company can tolerate losing up to 24 hours of data from its primary database. What does this 24-hour metric define? Options: A Recovery Time Objective (RTO) B Annualized Loss Expectancy (ALE) C Single Loss Expectancy (SLE) D Recovery Point Objective (RPO) Correct Option: D Recovery Point Objective (RPO) Keywords for Exam: RPO, RTO, BIA, disaster recovery, data loss tolerance Detailed Explanation:
The Recovery Point Objective (RPO) refers to the maximum acceptable amount of data loss an application can undergo, measured in time. It defines the point in time to which data must be restored to resume processing. An RPO of 24 hours means the backups must be recent enough that no more than 24 hours of data is lost.

** Question 35** Which physical security control is best suited for preventing tailgating? Options: A CCTV cameras B Security guards C Mantraps D Fences Correct Option: C Mantraps Keywords for Exam: tailgating, physical security, mantrap, access control Detailed Explanation:
A mantrap is a physical security access control system comprising a small space with two sets of interlocking doors, such that the first set of doors must close before the second set can be opened. This system effectively prevents tailgating by allowing only one authorized person to pass through at a time.

** Question 36** What is the primary function of a Security Information and Event Management (SIEM) system? Options: A To patch vulnerabilities in servers B To prevent network intrusions C To manage user access permissions D To aggregate, correlate, and analyze log data from various sources Correct Option: D To aggregate, correlate, and analyze log data from various sources Keywords for Exam: SIEM, logging, monitoring, correlation, security operations Detailed Explanation:
A SIEM system's primary function is to collect log data from a wide variety of sources (e.g., firewalls, servers, applications), normalize it, and perform real-time correlation and analysis to identify security events, potential threats, and policy violations.

** Question 37** A piece of malware that is dormant until a specific date or event occurs is called a: Options: A Logic bomb B Worm C Backdoor D Rootkit Correct Option: A Logic bomb Keywords for Exam: malware, logic bomb, time bomb, trigger, malicious code Detailed Explanation:
A logic bomb is a piece of code intentionally inserted into a software system that will set off a malicious function when specified conditions are met. A "time bomb" is a type of logic bomb where the trigger is a specific date or time.

** Question 38** Which of the following is NOT a phase of the NIST incident response lifecycle? Options: A Preparation B Containment C Legal Action D Post-Incident Activity Correct Option: C Legal Action Keywords for Exam: incident response, NIST, preparation, detection, containment, eradication, recovery Detailed Explanation:
The NIST incident response lifecycle consists of four main phases: Preparation; Detection and Analysis; Containment, Eradication, and Recovery; and Post-Incident Activity. While legal action may be a consequence of an incident, it is not considered a formal phase of the technical response process itself.

** Question 39** DNS (Domain Name System) primarily operates on which TCP/IP port? Options: A 80 B 443 C 22 D 53 Correct Option: D 53 Keywords for Exam: DNS, port 53, network protocol, UDP, TCP Detailed Explanation:
The Domain Name System (DNS) is a hierarchical and decentralized naming system for computers, services, or other resources connected to the Internet or a private network. It primarily uses UDP port 53, but can also use TCP port 53 for tasks like zone transfers.

** Question 40** The process of obscuring data such that it remains usable for development or testing without revealing the original sensitive information is known as: Options: A Data encryption B Data masking C Data hashing D Data destruction Correct Option: B Data masking Keywords for Exam: data masking, tokenization, data protection, PII, non-production environment Detailed Explanation:
Data masking, or data obfuscation, is the process of hiding original data with modified content (characters or other data). The goal is to create a structurally similar but inauthentic version of the organization's data that can be used in non-production environments (e.g., testing, development) without exposing the sensitive, real data.

** Question 41** An attacker sets up a fake Wi-Fi access point in a coffee shop that looks like the real, legitimate one. What is this type of attack called? Options: A Wardriving B Evil Twin C Bluesnarfing D IV Attack Correct Option: B Evil Twin Keywords for Exam: evil twin, wireless attack, rogue access point, man-in-the-middle Detailed Explanation:
An evil twin is a fraudulent Wi-Fi access point that appears to be legitimate but is set up to eavesdrop on wireless communications. It is the wireless equivalent of the phishing scam. This type of attack may be used to steal the passwords of unsuspecting users or to perform a man-in-the-middle attack.

** Question 42** Which access control model is the most restrictive and is often used in high-security environments like the military? Options: A Discretionary Access Control (DAC) B Role-Based Access Control (RBAC) C Mandatory Access Control (MAC) D Attribute-Based Access Control (ABAC) Correct Option: C Mandatory Access Control (MAC) Keywords for Exam: MAC, mandatory access control, labels, classification, high-security Detailed Explanation:
Mandatory Access Control (MAC) is the most restrictive access control model. In a MAC system, access is controlled by the operating system based on security labels assigned to subjects (users) and objects (files). Users cannot change these permissions, which makes it ideal for environments where confidentiality is paramount.

** Question 43** What type of security control are security awareness training sessions for employees? Options: A Technical B Physical C Administrative D Compensating Correct Option: C Administrative Keywords for Exam: security awareness, training, administrative control, preventive control Detailed Explanation:
Administrative controls are focused on people and processes. Security awareness training is a key administrative control designed to educate employees about security policies, procedures, and threats, thereby preventing security incidents caused by human error.

** Question 44** The first step in developing a Business Continuity Plan (BCP) is to: Options: A Conduct a Business Impact Analysis (BIA) B Create a disaster recovery plan C Secure an alternate site D Test the plan Correct Option: A Conduct a Business Impact Analysis (BIA) Keywords for Exam: BCP, BIA, business continuity, first step, planning Detailed Explanation:
The Business Impact Analysis (BIA) is the foundational first step of the BCP/DRP process. The BIA identifies critical business functions and the resources they depend on, and it determines the potential impact of a disruption. The results of the BIA drive all subsequent decisions in the continuity planning process.

** Question 45** Which of the following ensures that a sender cannot deny having sent a message? Options: A Encryption B Integrity C Authentication D Non-repudiation Correct Option: D Non-repudiation Keywords for Exam: non-repudiation, digital signature, integrity, authentication Detailed Explanation:
Non-repudiation is the assurance that someone cannot deny the validity of something. In cybersecurity, it is typically achieved with digital signatures, which provide proof of origin (authentication) and proof of data integrity, making it difficult for the sender to deny their actions.

** Question 46** Which type of backup only saves files that have changed since the last full backup? Options: A Incremental backup B Differential backup C Full backup D Snapshot Correct Option: B Differential backup Keywords for Exam: backup, differential, incremental, full, archive bit Detailed Explanation:
A differential backup copies all files that have changed since the last full backup was performed. Restoration is simpler than incremental because it only requires the last full backup and the most recent differential backup.

** Question 47** In cryptography, what is a private key? Options: A A key shared between two parties for symmetric encryption B A key available to anyone to encrypt messages C A secret key used in asymmetric encryption to decrypt messages D A temporary key used for a single session Correct Option: C A secret key used in asymmetric encryption to decrypt messages Keywords for Exam: private key, public key, asymmetric encryption, cryptography, confidentiality Detailed Explanation:
In asymmetric (public-key) cryptography, the private key is the secret half of a key pair that is known only to the owner. It is used to decrypt messages that were encrypted with the corresponding public key and to create digital signatures.

** Question 48** An attacker discovers a new vulnerability in a popular software application that is unknown to the vendor. What is this type of vulnerability called? Options: A Common Vulnerability and Exposure (CVE) B Zero-day vulnerability C Legacy vulnerability D Known vulnerability Correct Option: B Zero-day vulnerability Keywords for Exam: zero-day, vulnerability, exploit, patch, unknown Detailed Explanation:
A zero-day vulnerability is a flaw in software, hardware, or firmware that is unknown to the party or parties responsible for patching or otherwise fixing the flaw. Attackers can exploit these vulnerabilities before a patch is available, making them particularly dangerous.

** Question 49** What is the primary function of DHCP (Dynamic Host Configuration Protocol)? Options: A To translate domain names into IP addresses B To automatically assign IP addresses to devices on a network C To transfer files between a client and a server D To send email messages Correct Option: B To automatically assign IP addresses to devices on a network Keywords for Exam: DHCP, IP address, network management, automation Detailed Explanation:
DHCP is a network management protocol used on IP networks whereby a DHCP server dynamically assigns an IP address and other network configuration parameters to each device on a network so they can communicate with other IP networks. It automates the process of IP address configuration.

** Question 50** Which of the following is an example of a physical security control? Options: A Password policy B Firewall C Encryption D Fences Correct Option: D Fences Keywords for Exam: physical control, security control, fences, locks, guards Detailed Explanation:
Physical security controls are measures used to protect facilities, equipment, and resources from physical threats. This includes items like fences, walls, locks, security guards, and surveillance cameras. Password policies, firewalls, and encryption are examples of logical or technical controls.
`;
