
export const rawText4 = `
** Question 1** Which document provides high-level, mandatory directives set by senior management to dictate an organization's security posture? Options: A Standard B Guideline C Policy D Procedure Correct Option: C Policy Keywords for Exam: governance, policy, standard, guideline, procedure, senior management Detailed Explanation:
นโยบาย (Policy) คือแถลงการณ์อย่างเป็นทางการเกี่ยวกับเจตนาและทิศทางตามที่กำหนดโดยผู้บริหารระดับสูง ซึ่งมีผลบังคับใช้และเป็นรากฐานสำหรับเอกสารความปลอดภัยอื่นๆ ทั้งหมด มาตรฐาน (Standards) กำหนดข้อกำหนดเฉพาะสำหรับเทคโนโลยี, แนวทาง (Guidelines) ให้คำแนะนำ, และขั้นตอน (Procedures) ให้คำแนะนำทีละขั้นตอน

** Question 2** An organization is setting up a new data center and wants to ensure high availability for its critical servers. They decide to implement a system with multiple power supplies, redundant network cards, and clustered servers. This is an example of which security concept? Options: A Defense in depth B Least privilege C Redundancy D Separation of duties Correct Option: C Redundancy Keywords for Exam: high availability, availability, redundancy, fault tolerance, single point of failure Detailed Explanation:
การทำซ้ำซ้อน (Redundancy) คือการทำสำเนาส่วนประกอบหรือฟังก์ชันที่สำคัญของระบบโดยมีวัตถุประสงค์เพื่อเพิ่มความน่าเชื่อถือและความพร้อมใช้งาน ซึ่งจะช่วยขจัดจุด отказаเดียว (single points of failure) ส่วน Defense in depth เป็นแนวทางการรักษาความปลอดภัยแบบหลายชั้น ในขณะที่ Least privilege และ Separation of duties เป็นหลักการควบคุมการเข้าถึง

** Question 3** What is the primary purpose of a Business Impact Analysis (BIA)? Options: A To calculate the exact financial loss of a disaster B To identify and prioritize critical business functions and resources C To test the disaster recovery plan D To select a vendor for a hot site Correct Option: B To identify and prioritize critical business functions and resources Keywords for Exam: BIA, business impact analysis, business continuity, critical functions, RTO, RPO Detailed Explanation:
เป้าหมายหลักของการวิเคราะห์ผลกระทบทางธุรกิจ (BIA) คือการระบุฟังก์ชันทางธุรกิจที่สำคัญขององค์กรและประเมินผลกระทบที่การหยุดชะงักจะมีต่อฟังก์ชันเหล่านั้น การวิเคราะห์นี้มีความสำคัญอย่างยิ่งในการกำหนด Recovery Time Objectives (RTO) และ Recovery Point Objectives (RPO) และเป็นรากฐานของแผนความต่อเนื่องทางธุรกิจ (BCP)

** Question 4** A user receives an email that appears to be from their bank, asking them to click a link and verify their account details. This is a classic example of what type of attack? Options: A Whaling B Vishing C Smishing D Phishing Correct Option: D Phishing Keywords for Exam: phishing, social engineering, email, fraudulent message, credential harvesting Detailed Explanation:
ฟิชชิ่ง (Phishing) เป็นการโจมตีทางวิศวกรรมสังคมประเภทหนึ่งที่ผู้โจมตีส่งอีเมลหลอกลวงที่อ้างว่ามาจากแหล่งที่เชื่อถือได้เพื่อหลอกให้บุคคลเปิดเผยข้อมูลที่ละเอียดอ่อน เช่น รหัสผ่านและหมายเลขบัตรเครดิต Whaling คือฟิชชิ่งที่มุ่งเป้าไปที่ผู้บริหาร, Vishing คือฟิชชิ่งทางเสียง และ Smishing คือฟิชชิ่งทาง SMS

** Question 5** In the CIA triad, which principle ensures that data is not altered or destroyed in an unauthorized manner? Options: A Confidentiality B Integrity C Availability D Non-repudiation Correct Option: B Integrity Keywords for Exam: CIA triad, integrity, data alteration, accuracy, consistency, hashing Detailed Explanation:
ความสมบูรณ์ของข้อมูล (Integrity) คือตัว 'I' ใน CIA triad และหมายถึงการรักษาความสอดคล้อง, ความถูกต้อง และความน่าเชื่อถือของข้อมูลตลอดวงจรชีวิตของมัน เพื่อให้แน่ใจว่าข้อมูลไม่ได้รับการแก้ไขโดยไม่ได้รับอนุญาต การแฮชเป็นกลไกทั่วไปที่ใช้ในการตรวจสอบความสมบูรณ์ของข้อมูล

** Question 6** An organization wants to implement an access control model where permissions are assigned based on a user's job title, such as "Accountant" or "HR Manager". Which model would be most appropriate? Options: A Discretionary Access Control (DAC) B Mandatory Access Control (MAC) C Attribute-Based Access Control (ABAC) D Role-Based Access Control (RBAC) Correct Option: D Role-Based Access Control (RBAC) Keywords for Exam: access control, RBAC, role-based, job title, permissions, MAC, DAC, ABAC Detailed Explanation:
Role-Based Access Control (RBAC) เป็นโมเดลการควบคุมการเข้าถึงที่สิทธิ์จะถูกกำหนดให้กับบทบาท และผู้ใช้จะถูกกำหนดให้กับบทบาทเหล่านั้น ซึ่งช่วยให้การบริหารจัดการง่ายขึ้น เนื่องจากสามารถจัดการสิทธิ์สำหรับบทบาทแทนที่จะเป็นสำหรับผู้ใช้แต่ละคน เหมาะสำหรับองค์กรที่ฟังก์ชันของผู้ใช้ถูกกำหนดไว้อย่างดีตามตำแหน่งงาน

** Question 7** Which of the following is considered a 'preventive' security control? Options: A CCTV Camera B Firewall C Audit Log D Intrusion Detection System (IDS) Correct Option: B Firewall Keywords for Exam: security control, preventive, detective, corrective, firewall, IDS Detailed Explanation:
การควบคุมเชิงป้องกัน (Preventive control) ถูกออกแบบมาเพื่อหยุดยั้งเหตุการณ์ด้านความปลอดภัยไม่ให้เกิดขึ้น ไฟร์วอลล์เป็นตัวอย่างคลาสสิก เนื่องจากมันบล็อกทราฟฟิกเครือข่ายที่ไม่ได้รับอนุญาตอย่างแข็งขันตามชุดของกฎ กล้องวงจรปิดและ IDS เป็นการควบคุมเชิงตรวจจับ (detective controls) และบันทึกการตรวจสอบ (audit logs) ใช้สำหรับการตรวจจับและการสืบสวน

** Question 8** After a security incident, a forensic investigator is analyzing data that was left on a hard drive even after the files were deleted. What is this type of data called? Options: A Data in transit B Data remnants C Data in use D Temporary data Correct Option: B Data remnants Keywords for Exam: data remnants, data destruction, sanitization, residual data, forensics Detailed Explanation:
ข้อมูลตกค้าง (Data remnants) หรือข้อมูลที่เหลืออยู่ หมายถึงข้อมูลที่ยังคงอยู่บนสื่อบันทึกข้อมูลหลังจากขั้นตอนการลบข้อมูลทั่วไป ต้องใช้เทคนิคการทำลายหรือการล้างข้อมูลที่เหมาะสม เช่น การล้างสนามแม่เหล็ก (degaussing) หรือการลบด้วยการเข้ารหัส เพื่อกำจัดข้อมูลตกค้างและป้องกันการกู้คืน

** Question 9** An organization is choosing a disaster recovery site. They need a location that is fully equipped with hardware, software, and real-time data replication, allowing for an almost immediate switchover. What type of site is this? Options: A Hot site B Warm site C Cold site D Mobile site Correct Option: A Hot site Keywords for Exam: disaster recovery, recovery site, hot site, warm site, cold site, RTO Detailed Explanation:
Hot site คือศูนย์สำรองฉุกเฉินที่มีฟังก์ชันการทำงานครบถ้วน พร้อมฮาร์ดแวร์ ซอฟต์แวร์ และการจำลองข้อมูลแบบเรียลไทม์ที่จำเป็นทั้งหมด ซึ่งช่วยให้สามารถกู้คืนระบบได้เร็วที่สุด (RTO ต่ำที่สุด) แต่ก็เป็นตัวเลือกที่แพงที่สุด Warm site มีฮาร์ดแวร์แต่ต้องใช้เวลาในการกู้คืนข้อมูล และ Cold site เป็นเพียงพื้นที่ว่างที่มีไฟฟ้าและการเชื่อมต่อ

** Question 10** Which protocol is used to securely browse websites and encrypts the traffic between the browser and the web server? Options: A FTP B HTTP C SMTP D HTTPS Correct Option: D HTTPS Keywords for Exam: HTTPS, HTTP, TLS, SSL, encryption, port 443, network security Detailed Explanation:
HTTPS (Hypertext Transfer Protocol Secure) เป็นเวอร์ชันที่ปลอดภัยของ HTTP โดยใช้โปรโตคอลการเข้ารหัสเช่น TLS (Transport Layer Security) หรือ SSL (Secure Sockets Layer) เพื่อเข้ารหัสช่องทางการสื่อสาร ซึ่งช่วยปกป้องความลับและความสมบูรณ์ของข้อมูลที่แลกเปลี่ยนระหว่างเบราว์เซอร์ของผู้ใช้และเว็บไซต์ ทำงานบนพอร์ต 443

** Question 11** What is the main difference between symmetric and asymmetric encryption? Options: A Symmetric is faster than asymmetric B Symmetric uses two keys, while asymmetric uses one C Symmetric is only for data at rest, while asymmetric is for data in transit D Symmetric uses the same key for encryption and decryption, while asymmetric uses different keys Correct Option: D Symmetric uses the same key for encryption and decryption, while asymmetric uses different keys Keywords for Exam: encryption, symmetric, asymmetric, public key, private key, cryptography Detailed Explanation:
ความแตกต่างพื้นฐานอยู่ที่คีย์ที่ใช้ การเข้ารหัสแบบสมมาตร (Symmetric) ใช้คีย์เดียวร่วมกันในการเข้ารหัสและถอดรหัสข้อมูล ส่วนการเข้ารหัสแบบอสมมาตร (Asymmetric) หรือ Public-key ใช้คีย์คู่: Public key สำหรับเข้ารหัส และ Private key สำหรับถอดรหัส

** Question 12** According to the ISC2 Code of Ethics, acting honorably, honestly, justly, responsibly, and legally is part of which canon? Options: A Protect society, the common good B Act honorably, honestly, justly, responsibly, and legally C Provide diligent and competent service to principals D Advance and protect the profession Correct Option: B Act honorably, honestly, justly, responsibly, and legally Keywords for Exam: ISC2, ethics, canons, act honorably, due care Detailed Explanation:
นี่คือหลักจรรยาบรรณข้อที่สองของ ISC2 Code of Ethics ซึ่งกำหนดให้สมาชิกต้องรักษามาตรฐานการปฏิบัติงานระดับสูงและปฏิบัติตามกฎหมายและข้อบังคับทั้งหมด

** Question 13** A security administrator is configuring a system to require a password and a fingerprint scan for access. This is an implementation of what? Options: A Single-factor authentication B Two-person control C Multi-factor authentication D Defense in depth Correct Option: C Multi-factor authentication Keywords for Exam: authentication, MFA, multi-factor, something you know, something you are, something you have Detailed Explanation:
การยืนยันตัวตนแบบหลายปัจจัย (Multi-factor authentication - MFA) ต้องการให้ผู้ใช้ระบุปัจจัยการยืนยันตัวตนตั้งแต่สองประเภทขึ้นไป ในกรณีนี้ รหัสผ่านคือ 'สิ่งที่คุณรู้' (something you know) และลายนิ้วมือคือ 'สิ่งที่คุณเป็น' (something you are) การใช้ปัจจัยจากสองหมวดหมู่ที่แตกต่างกันถือเป็น MFA

** Question 14** What is the primary purpose of system hardening? Options: A To make the system run faster B To reduce the system's attack surface C To monitor system logs D To back up system data Correct Option: B To reduce the system's attack surface Keywords for Exam: hardening, configuration management, attack surface, security baseline Detailed Explanation:
การเสริมความแข็งแกร่งของระบบ (System hardening) คือกระบวนการรักษาความปลอดภัยของระบบโดยการลดช่องโหว่ ซึ่งทำได้โดยการลดพื้นที่การโจมตี (attack surface) ซึ่งรวมถึงการลบซอฟต์แวร์ที่ไม่จำเป็น, การปิดบริการที่ไม่ได้ใช้, การปิดพอร์ตที่ไม่ได้ใช้ และการใช้แพตช์ความปลอดภัย

** Question 15** A company has a policy that one person can approve invoices, but a different person must be the one to issue payments. This is an example of what security principle? Options: A Least privilege B Separation of duties C Two-person control D Job rotation Correct Option: B Separation of duties Keywords for Exam: separation of duties, access control, fraud detection, security principle Detailed Explanation:
การแบ่งแยกหน้าที่ (Separation of duties) เป็นหลักการด้านความปลอดภัยที่ป้องกันไม่ให้บุคคลคนเดียวสามารถควบคุมทุกด้านของงานที่สำคัญได้ โดยการแบ่งความรับผิดชอบ (การอนุมัติกับการจ่ายเงิน) บริษัทจะลดความเสี่ยงของการทุจริตและข้อผิดพลาด

** Question 16** An attacker floods a web server with so many requests that it becomes overwhelmed and cannot respond to legitimate users. What type of attack is this? Options: A Man-in-the-middle (MitM) B Denial of Service (DoS) C SQL Injection D Cross-Site Scripting (XSS) Correct Option: B Denial of Service (DoS) Keywords for Exam: DoS, DDoS, availability, network attack, flooding Detailed Explanation:
การโจมตีแบบปฏิเสธการให้บริการ (Denial of Service - DoS) มีเป้าหมายเพื่อทำให้เครื่องหรือทรัพยากรเครือข่ายไม่พร้อมใช้งานสำหรับผู้ใช้ที่ตั้งใจ โดยการขัดขวางบริการ ซึ่งโดยทั่วไปทำได้โดยการท่วมท้นเป้าหมายด้วยทราฟฟิกจำนวนมากหรือคำขอที่เป็นอันตราย ซึ่งเป็นการทำลายความพร้อมใช้งาน (availability)

** Question 17** Which document is a non-binding agreement between two or more parties that outlines the terms and details of an understanding, including each party's requirements and responsibilities? Options: A Service Level Agreement (SLA) B Memorandum of Understanding (MOU) C Business Partnership Agreement (BPA) D Interconnection Security Agreement (ISA) Correct Option: B Memorandum of Understanding (MOU) Keywords for Exam: agreement, MOU, SLA, non-binding, informal agreement Detailed Explanation:
บันทึกความเข้าใจ (Memorandum of Understanding - MOU) คือเอกสารที่อธิบายข้อตกลงทวิภาคีหรือพหุภาคีระหว่างฝ่ายต่างๆ ซึ่งแสดงถึงเจตนารมณ์ร่วมกันของฝ่ายต่างๆ ที่จะดำเนินการในแนวทางเดียวกัน มักใช้ในกรณีที่ฝ่ายต่างๆ ไม่ได้หมายถึงข้อผูกพันทางกฎหมาย หรือในสถานการณ์ที่ฝ่ายต่างๆ ไม่สามารถสร้างข้อตกลงที่บังคับใช้ได้ตามกฎหมาย มีความเป็นทางการน้อยกว่า SLA

** Question 18** Which type of malware is specifically designed to replicate itself and spread to other computers, typically over a network, without human intervention? Options: A Virus B Trojan C Rootkit D Worm Correct Option: D Worm Keywords for Exam: malware, worm, virus, self-replicating, network propagation Detailed Explanation:
หนอน (Worm) เป็นโปรแกรมมัลแวร์คอมพิวเตอร์แบบสแตนด์อโลนที่จำลองตัวเองเพื่อแพร่กระจายไปยังคอมพิวเตอร์เครื่องอื่น มักใช้เครือข่ายคอมพิวเตอร์เพื่อแพร่กระจายตัวเอง โดยอาศัยความล้มเหลวในการรักษาความปลอดภัยบนคอมพิวเตอร์เป้าหมายเพื่อเข้าถึง ซึ่งแตกต่างจากไวรัสตรงที่ไม่ต้องแนบตัวเองกับโปรแกรมที่มีอยู่และไม่ต้องอาศัยการกระทำของมนุษย์ในการแพร่กระจาย

** Question 19** What does a hash function provide? Options: A Confidentiality B Availability C Integrity D Authorization Correct Option: C Integrity Keywords for Exam: hashing, integrity, message digest, digital fingerprint, one-way function Detailed Explanation:
ฟังก์ชันแฮชรับอินพุต (หรือ 'ข้อความ') และส่งคืนสตริงไบต์ที่มีขนาดคงที่ ผลลัพธ์ที่ได้คือ 'แฮช' หรือ 'message digest' ซึ่งเป็นลายนิ้วมือดิจิทัลที่ไม่ซ้ำกันของข้อมูล หากข้อมูลอินพุตเปลี่ยนแปลงไปแม้เพียงเล็กน้อย ค่าแฮชจะเปลี่ยนแปลงไปโดยสิ้นเชิง คุณสมบัตินี้ทำให้การแฮชสามารถใช้ในการตรวจสอบความสมบูรณ์ของข้อมูลได้

** Question 20** An organization's acceptable use policy (AUP) is what type of security control? Options: A Physical B Technical C Administrative D Corrective Correct Option: C Administrative Keywords for Exam: security control, administrative, policy, AUP, preventive control Detailed Explanation:
การควบคุมเชิงบริหาร (Administrative controls) คือนโยบาย, ขั้นตอน, มาตรฐาน และแนวทางที่กำกับการจัดการความปลอดภัยภายในองค์กร นโยบายการใช้งานที่ยอมรับได้ (AUP) เป็นเอกสารที่กำหนดกฎที่ผู้ใช้ต้องยอมรับเพื่อใช้เครือข่ายหรือบริการ ทำให้เป็นตัวอย่างคลาสสิกของการควบคุมเชิงบริหาร

** Question 21** In the context of risk management, if an organization decides to purchase cybersecurity insurance, which risk treatment strategy are they employing? Options: A Risk Acceptance B Risk Mitigation C Risk Avoidance D Risk Transference Correct Option: D Risk Transference Keywords for Exam: risk management, risk transference, risk mitigation, insurance Detailed Explanation:
การถ่ายโอนความเสี่ยง (Risk transference) หรือการแบ่งปันความเสี่ยง คือกลยุทธ์ในการย้ายผลกระทบทางการเงินของความเสี่ยงไปยังบุคคลที่สาม การซื้อกรมธรรม์ประกันภัยเป็นตัวอย่างที่พบบ่อยที่สุดของเรื่องนี้ โดยที่ความรับผิดทางการเงินสำหรับการละเมิดความปลอดภัยจะถูกโอนไปยังบริษัทประกันภัย

** Question 22** Which layer of the OSI model is responsible for routing and forwarding IP packets? Options: A Layer 2 (Data Link) B Layer 3 (Network) C Layer 4 (Transport) D Layer 7 (Application) Correct Option: B Layer 3 (Network) Keywords for Exam: OSI model, network layer, layer 3, routing, IP address, router Detailed Explanation:
ชั้นเครือข่าย (Network Layer - Layer 3) รับผิดชอบการกำหนดที่อยู่เชิงตรรกะ (IP addresses) และการกำหนดเส้นทางที่ดีที่สุดสำหรับข้อมูลที่จะเดินทางจากต้นทางไปยังปลายทางผ่านเครือข่ายหลายเครือข่าย เราเตอร์ทำงานที่ชั้นนี้เพื่อทำการตัดสินใจในการส่งต่อข้อมูล

** Question 23** The final step in most incident response frameworks, such as the one from NIST, involves reviewing the incident and the team's performance to improve for the future. What is this phase called? Options: A Containment B Eradication C Recovery D Post-Incident Activity (or Lessons Learned) Correct Option: D Post-Incident Activity (or Lessons Learned) Keywords for Exam: incident response, NIST, lessons learned, post-incident, preparation Detailed Explanation:
ขั้นตอนกิจกรรมหลังเกิดเหตุ (Post-Incident Activity) เป็นขั้นตอนสุดท้ายในวงจรชีวิตการตอบสนองต่อเหตุการณ์ของ NIST (SP 800-61) ซึ่งเกี่ยวข้องกับการวิเคราะห์เหตุการณ์และการตอบสนองต่อเหตุการณ์นั้นเพื่อระบุบทเรียนที่ได้รับ วงจรความคิดเห็นนี้มีความสำคัญอย่างยิ่งต่อการปรับปรุงการควบคุมความปลอดภัยและกระบวนการตอบสนองต่อเหตุการณ์เพื่อให้สามารถรับมือกับเหตุการณ์ในอนาคตได้ดีขึ้น

** Question 24** A firewall that inspects not only the packet header but also the data content of the packets to look for malicious activity is what kind of firewall? Options: A Packet-filtering firewall B Stateful inspection firewall C Next-generation firewall (NGFW) D Proxy firewall Correct Option: C Next-generation firewall (NGFW) Keywords for Exam: firewall, NGFW, deep packet inspection, application awareness Detailed Explanation:
ไฟร์วอลล์รุ่นใหม่ (Next-Generation Firewall - NGFW) ทำได้มากกว่าการตรวจสอบพอร์ต/โปรโตคอลแบบดั้งเดิม โดยมีคุณสมบัติต่างๆ เช่น การตรวจสอบแพ็คเก็ตในระดับลึก (DPI), การรับรู้แอปพลิเคชัน และความสามารถในการป้องกันการบุกรุก ซึ่งช่วยให้สามารถตัดสินใจเกี่ยวกับทราฟฟิกได้อย่างชาญฉลาดมากขึ้นโดยพิจารณาจากเนื้อหา ไม่ใช่แค่ข้อมูลส่วนหัว

** Question 25** What security concept is violated when an administrator uses a shared account with a single password for all network devices? Options: A Confidentiality B Defense in Depth C Accountability D Availability Correct Option: C Accountability Keywords for Exam: accountability, non-repudiation, shared account, logging, auditing Detailed Explanation:
ความรับผิดชอบ (Accountability) ทำให้แน่ใจได้ว่าการกระทำของบุคคลหรือระบบสามารถตรวจสอบย้อนกลับไปยังหน่วยงานนั้นๆ ได้อย่างเฉพาะเจาะจง เมื่อใช้บัญชีที่ใช้ร่วมกัน เป็นไปไม่ได้ที่จะรู้ว่าบุคคลใดเป็นผู้กระทำการนั้นๆ ซึ่งเป็นการทำลายความรับผิดชอบและแนวคิดที่เกี่ยวข้องคือการห้ามปฏิเสธความรับผิดชอบ (non-repudiation)

** Question 26** Which of the following is an example of 'something you are' in authentication? Options: A A hardware token B A PIN code C A fingerprint D A smart card Correct Option: C A fingerprint Keywords for Exam: authentication factors, something you are, biometrics, MFA Detailed Explanation:
'สิ่งที่คุณเป็น' (Something you are) หมายถึงปัจจัยการพิสูจน์ตัวตนทางชีวภาพ (biometric) ซึ่งเป็นลักษณะเฉพาะทางกายภาพของบุคคล เช่น ลายนิ้วมือ, รูปแบบม่านตา หรือลักษณะใบหน้า รหัสผ่านและ PIN เป็น 'สิ่งที่คุณรู้' (something you know) ในขณะที่โทเค็นและสมาร์ทการ์ดเป็น 'สิ่งที่คุณมี' (something you have)

** Question 27** What does the principle of "least privilege" dictate? Options: A Users should have the maximum privileges needed to do their job and a little extra. B Users should have privileges assigned based on their role in the company. C Users should only be granted the minimum permissions necessary to perform their job functions. D Users should have their privileges reviewed at least once per year. Correct Option: C Users should only be granted the minimum permissions necessary to perform their job functions. Keywords for Exam: least privilege, access control, permissions, need-to-know Detailed Explanation:
หลักการสิทธิ์น้อยที่สุด (Least privilege) เป็นรากฐานสำคัญของการควบคุมการเข้าถึง โดยระบุว่าผู้ใช้, โปรแกรม หรือกระบวนการควรมีสิทธิ์ขั้นต่ำที่จำเป็นในการปฏิบัติงานเฉพาะที่ได้รับอนุญาตเท่านั้น ซึ่งจะช่วยจำกัดความเสียหายที่อาจเกิดขึ้นจากอุบัติเหตุ, ข้อผิดพลาด หรือการใช้ข้อมูลประจำตัวในทางที่ผิด

** Question 28** An organization has determined that its critical sales system can be down for a maximum of 4 hours before causing significant business harm. What does this 4-hour window represent? Options: A Recovery Point Objective (RPO) B Mean Time To Repair (MTTR) C Recovery Time Objective (RTO) D Mean Time Between Failures (MTBF) Correct Option: C Recovery Time Objective (RTO) Keywords for Exam: RTO, RPO, BIA, disaster recovery, business continuity Detailed Explanation:
Recovery Time Objective (RTO) คือระยะเวลาเป้าหมายที่กระบวนการทางธุรกิจจะต้องได้รับการกู้คืนหลังจากเกิดภัยพิบัติหรือการหยุดชะงัก เพื่อหลีกเลี่ยงผลกระทบที่ยอมรับไม่ได้ที่เกี่ยวข้องกับการหยุดชะงักของความต่อเนื่องทางธุรกิจ ในกรณีนี้ RTO คือ 4 ชั่วโมง

** Question 29** What is the process of securely and permanently removing data from a storage medium called? Options: A Data Archiving B Data Encryption C Data Masking D Data Sanitization Correct Option: D Data Sanitization Keywords for Exam: data sanitization, data destruction, degaussing, cryptographic erase, data remnants Detailed Explanation:
การล้างข้อมูล (Data sanitization) คือกระบวนการลบหรือทำลายข้อมูลที่จัดเก็บไว้ในอุปกรณ์หน่วยความจำอย่างจงใจ, ถาวร และไม่สามารถย้อนกลับได้ โดยมีวัตถุประสงค์เพื่อทำให้ข้อมูลไม่สามารถกู้คืนได้ วิธีการต่างๆ ได้แก่ การเขียนทับ, การล้างสนามแม่เหล็ก และการทำลายทางกายภาพ

** Question 30** Which cloud computing service model provides the customer with a complete application that is managed by the provider? Options: A Infrastructure as a Service (IaaS) B Platform as a Service (PaaS) C Software as a Service (SaaS) D Anything as a Service (XaaS) Correct Option: C Software as a Service (SaaS) Keywords for Exam: cloud service models, SaaS, PaaS, IaaS, shared responsibility Detailed Explanation:
ในโมเดล Software as a Service (SaaS) ผู้ให้บริการคลาวด์จะจัดส่งและจัดการแอปพลิเคชันที่สมบูรณ์ผ่านทางอินเทอร์เน็ต ลูกค้าเพียงแค่ใช้ซอฟต์แวร์โดยไม่ต้องกังวลเกี่ยวกับโครงสร้างพื้นฐาน, แพลตฟอร์ม หรือการบำรุงรักษาแอปพลิเคชันเบื้องหลัง ตัวอย่างเช่น อีเมลบนเว็บและซอฟต์แวร์ CRM

** Question 31** Which security goal is most compromised by a ransomware attack? Options: A Confidentiality B Integrity C Availability D Non-repudiation Correct Option: C Availability Keywords for Exam: ransomware, availability, CIA triad, encryption, malware Detailed Explanation:
แรนซัมแวร์ทำงานโดยการเข้ารหัสไฟล์ของเหยื่อ ทำให้ไม่สามารถเข้าถึงได้ เนื่องจากผู้ใช้ที่ได้รับอนุญาตไม่สามารถเข้าถึงข้อมูลของตนเองได้อีกต่อไป นี่จึงเป็นการโจมตีโดยตรงต่อหลักการความพร้อมใช้งาน (Availability) แม้ว่าความลับและความสมบูรณ์ของข้อมูลอาจถูกบุกรุกได้เช่นกัน แต่ผลกระทบหลักและทันทีคือความพร้อมใช้งาน

** Question 32** Which document is a mandatory, organization-wide directive that dictates acceptable and unacceptable actions? Options: A Standard B Guideline C Policy D Procedure Correct Option: C Policy Keywords for Exam: governance, policy, standard, mandatory, high-level Detailed Explanation:
นโยบาย (Policy) เป็นเอกสารระดับสูงที่มีผลบังคับใช้และใช้กับทั้งองค์กร สร้างขึ้นโดยผู้บริหารระดับสูงและกำหนดทิศทางเชิงกลยุทธ์ด้านความปลอดภัย นโยบายระบุว่า *ต้อง* ทำอะไร แต่ไม่ได้ระบุว่า *ทำอย่างไร*

** Question 33** What is the term for an attack that tricks a user into clicking on a malicious link by hiding it under legitimate-looking text or images? Options: A Clickjacking B Phishing C Typosquatting D Spoofing Correct Option: A Clickjacking Keywords for Exam: clickjacking, UI redress attack, social engineering, web attack Detailed Explanation:
Clickjacking หรือที่เรียกว่า UI redress attack เป็นเทคนิคที่เป็นอันตรายในการหลอกลวงให้ผู้ใช้คลิกสิ่งที่แตกต่างจากที่ผู้ใช้รับรู้ ซึ่งอาจนำไปสู่การเปิดเผยข้อมูลที่เป็นความลับหรือการควบคุมคอมพิวเตอร์ของพวกเขาในขณะที่คลิกบนหน้าเว็บที่ดูเหมือนไม่มีอะไร

** Question 34** A security team is performing a Business Impact Analysis (BIA). They determine that in a disaster, the company can tolerate losing up to 24 hours of data from its primary database. What does this 24-hour metric define? Options: A Recovery Time Objective (RTO) B Annualized Loss Expectancy (ALE) C Single Loss Expectancy (SLE) D Recovery Point Objective (RPO) Correct Option: D Recovery Point Objective (RPO) Keywords for Exam: RPO, RTO, BIA, disaster recovery, data loss tolerance Detailed Explanation:
Recovery Point Objective (RPO) หมายถึงจำนวนข้อมูลสูงสุดที่ยอมรับได้ที่แอปพลิเคชันสามารถสูญเสียได้ ซึ่งวัดเป็นเวลา โดยจะกำหนดจุดเวลาที่ต้องกู้คืนข้อมูลเพื่อกลับมาดำเนินการต่อ RPO 24 ชั่วโมงหมายความว่าข้อมูลสำรองต้องใหม่เพียงพอที่จะทำให้ข้อมูลที่สูญเสียไปไม่เกิน 24 ชั่วโมง

** Question 35** Which physical security control is best suited for preventing tailgating? Options: A CCTV cameras B Security guards C Mantraps D Fences Correct Option: C Mantraps Keywords for Exam: tailgating, physical security, mantrap, access control Detailed Explanation:
Mantrap เป็นระบบควบคุมการเข้าถึงทางกายภาพที่ประกอบด้วยพื้นที่ขนาดเล็กที่มีประตูสองชุดที่ทำงานประสานกัน โดยที่ประตูชุดแรกต้องปิดก่อนที่ประตูชุดที่สองจะเปิดได้ ระบบนี้ช่วยป้องกันการเดินตาม (tailgating) ได้อย่างมีประสิทธิภาพโดยอนุญาตให้ผู้ที่ได้รับอนุญาตผ่านได้ทีละคน

** Question 36** What is the primary function of a Security Information and Event Management (SIEM) system? Options: A To patch vulnerabilities in servers B To prevent network intrusions C To manage user access permissions D To aggregate, correlate, and analyze log data from various sources Correct Option: D To aggregate, correlate, and analyze log data from various sources Keywords for Exam: SIEM, logging, monitoring, correlation, security operations Detailed Explanation:
หน้าที่หลักของระบบ SIEM คือการรวบรวมข้อมูลบันทึกจากแหล่งต่างๆ ที่หลากหลาย (เช่น ไฟร์วอลล์, เซิร์ฟเวอร์, แอปพลิเคชัน), ทำให้เป็นมาตรฐาน และทำการวิเคราะห์และเชื่อมโยงข้อมูลแบบเรียลไทม์เพื่อระบุเหตุการณ์ด้านความปลอดภัย, ภัยคุกคามที่อาจเกิดขึ้น และการละเมิดนโยบาย

** Question 37** A piece of malware that is dormant until a specific date or event occurs is called a: Options: A Logic bomb B Worm C Backdoor D Rootkit Correct Option: A Logic bomb Keywords for Exam: malware, logic bomb, time bomb, trigger, malicious code Detailed Explanation:
Logic bomb คือโค้ดที่ถูกจงใจแทรกเข้าไปในระบบซอฟต์แวร์ซึ่งจะเรียกใช้ฟังก์ชันที่เป็นอันตรายเมื่อตรงตามเงื่อนไขที่ระบุไว้ "Time bomb" เป็นประเภทหนึ่งของ logic bomb ที่ทริกเกอร์คือวันที่หรือเวลาที่ระบุ

** Question 38** Which of the following is NOT a phase of the NIST incident response lifecycle? Options: A Preparation B Containment C Legal Action D Post-Incident Activity Correct Option: C Legal Action Keywords for Exam: incident response, NIST, preparation, detection, containment, eradication, recovery Detailed Explanation:
วงจรชีวิตการตอบสนองต่อเหตุการณ์ของ NIST ประกอบด้วยสี่ขั้นตอนหลัก: การเตรียมการ (Preparation); การตรวจจับและวิเคราะห์ (Detection and Analysis); การจำกัดขอบเขต, การกำจัด และการกู้คืน (Containment, Eradication, and Recovery); และกิจกรรมหลังเกิดเหตุ (Post-Incident Activity) แม้ว่าการดำเนินการทางกฎหมายอาจเป็นผลมาจากเหตุการณ์ แต่ก็ไม่ถือเป็นขั้นตอนอย่างเป็นทางการของกระบวนการตอบสนองทางเทคนิค

** Question 39** DNS (Domain Name System) primarily operates on which TCP/IP port? Options: A 80 B 443 C 22 D 53 Correct Option: D 53 Keywords for Exam: DNS, port 53, network protocol, UDP, TCP Detailed Explanation:
Domain Name System (DNS) เป็นระบบการตั้งชื่อแบบลำดับชั้นและกระจายอำนาจสำหรับคอมพิวเตอร์, บริการ หรือทรัพยากรอื่นๆ ที่เชื่อมต่อกับอินเทอร์เน็ตหรือเครือข่ายส่วนตัว โดยส่วนใหญ่ใช้ UDP พอร์ต 53 แต่ก็สามารถใช้ TCP พอร์ต 53 สำหรับงานต่างๆ เช่น การถ่ายโอนโซน (zone transfers)

** Question 40** The process of obscuring data such that it remains usable for development or testing without revealing the original sensitive information is known as: Options: A Data encryption B Data masking C Data hashing D Data destruction Correct Option: B Data masking Keywords for Exam: data masking, tokenization, data protection, PII, non-production environment Detailed Explanation:
การปิดบังข้อมูล (Data masking) หรือการทำให้ข้อมูลคลุมเครือ คือกระบวนการซ่อนข้อมูลดั้งเดิมด้วยเนื้อหาที่แก้ไขแล้ว (ตัวอักษรหรือข้อมูลอื่น ๆ) เป้าหมายคือการสร้างเวอร์ชันของข้อมูลขององค์กรที่มีโครงสร้างคล้ายกันแต่ไม่เป็นของจริง ซึ่งสามารถใช้ในสภาพแวดล้อมที่ไม่ใช่การใช้งานจริง (เช่น การทดสอบ, การพัฒนา) โดยไม่ต้องเปิดเผยข้อมูลที่ละเอียดอ่อนและเป็นจริง

** Question 41** An attacker sets up a fake Wi-Fi access point in a coffee shop that looks like the real, legitimate one. What is this type of attack called? Options: A Wardriving B Evil Twin C Bluesnarfing D IV Attack Correct Option: B Evil Twin Keywords for Exam: evil twin, wireless attack, rogue access point, man-in-the-middle Detailed Explanation:
Evil twin คือจุดเข้าถึง Wi-Fi ปลอมที่ดูเหมือนถูกกฎหมาย แต่ถูกตั้งค่าขึ้นเพื่อดักฟังการสื่อสารไร้สาย เป็นการหลอกลวงที่เทียบเท่ากับการฟิชชิ่งในโลกไร้สาย การโจมตีประเภทนี้อาจใช้เพื่อขโมยรหัสผ่านของผู้ใช้ที่ไม่สงสัยหรือเพื่อดำเนินการโจมตีแบบ Man-in-the-middle

** Question 42** Which access control model is the most restrictive and is often used in high-security environments like the military? Options: A Discretionary Access Control (DAC) B Role-Based Access Control (RBAC) C Mandatory Access Control (MAC) D Attribute-Based Access Control (ABAC) Correct Option: C Mandatory Access Control (MAC) Keywords for Exam: MAC, mandatory access control, labels, classification, high-security Detailed Explanation:
Mandatory Access Control (MAC) เป็นโมเดลการควบคุมการเข้าถึงที่เข้มงวดที่สุด ในระบบ MAC การเข้าถึงจะถูกควบคุมโดยระบบปฏิบัติการตามป้ายกำกับความปลอดภัยที่กำหนดให้กับประธาน (ผู้ใช้) และกรรม (ไฟล์) ผู้ใช้ไม่สามารถเปลี่ยนแปลงสิทธิ์เหล่านี้ได้ ซึ่งทำให้เหมาะสำหรับสภาพแวดล้อมที่ความลับเป็นสิ่งสำคัญยิ่ง

** Question 43** What type of security control are security awareness training sessions for employees? Options: A Technical B Physical C Administrative D Compensating Correct Option: C Administrative Keywords for Exam: security awareness, training, administrative control, preventive control Detailed Explanation:
การควบคุมเชิงบริหารมุ่งเน้นไปที่คนและกระบวนการ การฝึกอบรมสร้างความตระหนักด้านความปลอดภัยเป็นการควบคุมเชิงบริหารที่สำคัญซึ่งออกแบบมาเพื่อให้ความรู้แก่พนักงานเกี่ยวกับนโยบาย, ขั้นตอน และภัยคุกคามด้านความปลอดภัย ซึ่งจะช่วยป้องกันเหตุการณ์ด้านความปลอดภัยที่เกิดจากความผิดพลาดของมนุษย์

** Question 44** The first step in developing a Business Continuity Plan (BCP) is to: Options: A Conduct a Business Impact Analysis (BIA) B Create a disaster recovery plan C Secure an alternate site D Test the plan Correct Option: A Conduct a Business Impact Analysis (BIA) Keywords for Exam: BCP, BIA, business continuity, first step, planning Detailed Explanation:
การวิเคราะห์ผลกระทบทางธุรกิจ (BIA) เป็นขั้นตอนแรกที่เป็นรากฐานของกระบวนการ BCP/DRP BIA จะระบุฟังก์ชันทางธุรกิจที่สำคัญและทรัพยากรที่ต้องพึ่งพา และกำหนดผลกระทบที่อาจเกิดขึ้นจากการหยุดชะงัก ผลลัพธ์ของ BIA จะเป็นตัวขับเคลื่อนการตัดสินใจทั้งหมดในกระบวนการวางแผนความต่อเนื่อง

** Question 45** Which of the following ensures that a sender cannot deny having sent a message? Options: A Encryption B Integrity C Authentication D Non-repudiation Correct Option: D Non-repudiation Keywords for Exam: non-repudiation, digital signature, integrity, authentication Detailed Explanation:
การห้ามปฏิเสธความรับผิดชอบ (Non-repudiation) คือการรับรองว่าบุคคลไม่สามารถปฏิเสธความถูกต้องของบางสิ่งได้ ในด้านความปลอดภัยทางไซเบอร์ โดยทั่วไปจะทำได้ด้วยลายเซ็นดิจิทัล ซึ่งให้หลักฐานของแหล่งกำเนิด (authentication) และหลักฐานของความสมบูรณ์ของข้อมูล (integrity) ทำให้ผู้ส่งปฏิเสธการกระทำของตนได้ยาก

** Question 46** Which type of backup only saves files that have changed since the last full backup? Options: A Incremental backup B Differential backup C Full backup D Snapshot Correct Option: B Differential backup Keywords for Exam: backup, differential, incremental, full, archive bit Detailed Explanation:
การสำรองข้อมูลแบบ Differential จะคัดลอกไฟล์ทั้งหมดที่มีการเปลี่ยนแปลงตั้งแต่การสำรองข้อมูลแบบเต็มครั้งล่าสุด การกู้คืนทำได้ง่ายกว่าแบบ Incremental เพราะต้องการเพียงข้อมูลสำรองแบบเต็มล่าสุดและข้อมูลสำรองแบบ Differential ล่าสุดเท่านั้น

** Question 47** In cryptography, what is a private key? Options: A A key shared between two parties for symmetric encryption B A key available to anyone to encrypt messages C A secret key used in asymmetric encryption to decrypt messages D A temporary key used for a single session Correct Option: C A secret key used in asymmetric encryption to decrypt messages Keywords for Exam: private key, public key, asymmetric encryption, cryptography, confidentiality Detailed Explanation:
ในการเข้ารหัสแบบอสมมาตร (public-key) private key คือครึ่งหนึ่งของคู่คีย์ที่เป็นความลับซึ่งเจ้าของเท่านั้นที่รู้ ใช้สำหรับถอดรหัสข้อความที่เข้ารหัสด้วย public key ที่สอดคล้องกัน และเพื่อสร้างลายเซ็นดิจิทัล

** Question 48** An attacker discovers a new vulnerability in a popular software application that is unknown to the vendor. What is this type of vulnerability called? Options: A Common Vulnerability and Exposure (CVE) B Zero-day vulnerability C Legacy vulnerability D Known vulnerability Correct Option: B Zero-day vulnerability Keywords for Exam: zero-day, vulnerability, exploit, patch, unknown Detailed Explanation:
ช่องโหว่ Zero-day คือข้อบกพร่องในซอฟต์แวร์, ฮาร์ดแวร์ หรือเฟิร์มแวร์ที่ไม่เป็นที่รู้จักของผู้รับผิดชอบในการแก้ไขหรือซ่อมแซมข้อบกพร่องนั้น ผู้โจมตีสามารถใช้ประโยชน์จากช่องโหว่เหล่านี้ก่อนที่จะมีแพตช์ออกมา ซึ่งทำให้เป็นอันตรายอย่างยิ่ง

** Question 49** What is the primary function of DHCP (Dynamic Host Configuration Protocol)? Options: A To translate domain names into IP addresses B To automatically assign IP addresses to devices on a network C To transfer files between a client and a server D To send email messages Correct Option: B To automatically assign IP addresses to devices on a network Keywords for Exam: DHCP, IP address, network management, automation Detailed Explanation:
DHCP เป็นโปรโตคอลการจัดการเครือข่ายที่ใช้บนเครือข่าย IP โดยเซิร์ฟเวอร์ DHCP จะกำหนดที่อยู่ IP และพารามิเตอร์การกำหนดค่าเครือข่ายอื่น ๆ ให้กับแต่ละอุปกรณ์บนเครือข่ายโดยอัตโนมัติ เพื่อให้สามารถสื่อสารกับเครือข่าย IP อื่น ๆ ได้ ซึ่งเป็นการทำให้กระบวนการกำหนดค่าที่อยู่ IP เป็นไปโดยอัตโนมัติ

** Question 50** Which of the following is an example of a physical security control? Options: A Password policy B Firewall C Encryption D Fences Correct Option: D Fences Keywords for Exam: physical control, security control, fences, locks, guards Detailed Explanation:
การควบคุมความปลอดภัยทางกายภาพเป็นมาตรการที่ใช้เพื่อปกป้องสิ่งอำนวยความสะดวก, อุปกรณ์ และทรัพยากรจากภัยคุกคามทางกายภาพ ซึ่งรวมถึงสิ่งของต่างๆ เช่น รั้ว, กำแพง, ล็อค, เจ้าหน้าที่รักษาความปลอดภัย และกล้องวงจรปิด นโยบายรหัสผ่าน, ไฟร์วอลล์ และการเข้ารหัสเป็นตัวอย่างของการควบคุมเชิงตรรกะหรือทางเทคนิค
`;
